//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelChecker.WEB.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО &quot;Академия БИМ&quot;.
        /// </summary>
        public static string Bimacad {
            get {
                return ResourceManager.GetString("Bimacad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матрица по категориям.
        /// </summary>
        public static string CategoryMatrix {
            get {
                return ResourceManager.GetString("CategoryMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория элементов.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Динамика.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор A.
        /// </summary>
        public static string CheckA {
            get {
                return ResourceManager.GetString("CheckA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор B.
        /// </summary>
        public static string CheckB {
            get {
                return ResourceManager.GetString("CheckB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование проверки.
        /// </summary>
        public static string CheckName {
            get {
                return ResourceManager.GetString("CheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфликты.
        /// </summary>
        public static string Clashes {
            get {
                return ResourceManager.GetString("Clashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет по проверкам.
        /// </summary>
        public static string ClashesReport {
            get {
                return ResourceManager.GetString("ClashesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверки и статусы.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование объекта.
        /// </summary>
        public static string ConstructionName {
            get {
                return ResourceManager.GetString("ConstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период хранения данных, мес.
        /// </summary>
        public static string DatRetentionPeriod {
            get {
                return ResourceManager.GetString("DatRetentionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделитель.
        /// </summary>
        public static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец периода.
        /// </summary>
        public static string EDate {
            get {
                return ResourceManager.GetString("EDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить ключ лицензии.
        /// </summary>
        public static string EditLicenseKey {
            get {
                return ResourceManager.GetString("EditLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на последние 3 мес..
        /// </summary>
        public static string Last3MonthsCapt {
            get {
                return ResourceManager.GetString("Last3MonthsCapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использования (3 мес).
        /// </summary>
        public static string Last3MonthsQnt {
            get {
                return ResourceManager.GetString("Last3MonthsQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дней пользования (3 мес).
        /// </summary>
        public static string Last3MonthsUniqQnt {
            get {
                return ResourceManager.GetString("Last3MonthsUniqQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя активность.
        /// </summary>
        public static string LastActivites {
            get {
                return ResourceManager.GetString("LastActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лицензия.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ лицензии.
        /// </summary>
        public static string LicenseKey {
            get {
                return ResourceManager.GetString("LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ключ лицензии.
        /// </summary>
        public static string LicenseNullKeyMsg {
            get {
                return ResourceManager.GetString("LicenseNullKeyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество рабочих мест.
        /// </summary>
        public static string LicenseQnt {
            get {
                return ResourceManager.GetString("LicenseQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лицензия действительна до.
        /// </summary>
        public static string LicenseSuccessMsg {
            get {
                return ResourceManager.GetString("LicenseSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок действия лицензии истек.
        /// </summary>
        public static string LicenseTimeOutMsg {
            get {
                return ResourceManager.GetString("LicenseTimeOutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество пользователей.
        /// </summary>
        public static string LicenseUsedQnt {
            get {
                return ResourceManager.GetString("LicenseUsedQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный ключ лицензии.
        /// </summary>
        public static string LicenseWrongKeyMsg {
            get {
                return ResourceManager.GetString("LicenseWrongKeyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нулевое число клиентских лицензий.
        /// </summary>
        public static string LicenseZeroQntMsg {
            get {
                return ResourceManager.GetString("LicenseZeroQntMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матрица моделей.
        /// </summary>
        public static string ModelMatrix {
            get {
                return ResourceManager.GetString("ModelMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель Revit.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено ни одного объекта.
        /// </summary>
        public static string NotFoundConstructions {
            get {
                return ResourceManager.GetString("NotFoundConstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на текущ..
        /// </summary>
        public static string NowCapt {
            get {
                return ResourceManager.GetString("NowCapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено данных по заданным параметрам.
        /// </summary>
        public static string NullCollection {
            get {
                return ResourceManager.GetString("NullCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбрано ни одного элемента.
        /// </summary>
        public static string NullListMsg {
            get {
                return ResourceManager.GetString("NullListMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя компьютера.
        /// </summary>
        public static string PCName {
            get {
                return ResourceManager.GetString("PCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные будут удалены, продолжить ?.
        /// </summary>
        public static string RemoveConfirmMsg {
            get {
                return ResourceManager.GetString("RemoveConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало периода.
        /// </summary>
        public static string SDate {
            get {
                return ResourceManager.GetString("SDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активные.
        /// </summary>
        public static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проанализированные.
        /// </summary>
        public static string StatusAnalized {
            get {
                return ResourceManager.GetString("StatusAnalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвержденные.
        /// </summary>
        public static string StatusConfirmed {
            get {
                return ResourceManager.GetString("StatusConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исправленные.
        /// </summary>
        public static string StatusCorrected {
            get {
                return ResourceManager.GetString("StatusCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые.
        /// </summary>
        public static string StatusCreate {
            get {
                return ResourceManager.GetString("StatusCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные сохранены.
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные успешно удалены.
        /// </summary>
        public static string SuccessRemoveMsg {
            get {
                return ResourceManager.GetString("SuccessRemoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Освободить лицензии.
        /// </summary>
        public static string WithdrawLicense {
            get {
                return ResourceManager.GetString("WithdrawLicense", resourceCulture);
            }
        }
    }
}
